#!/bin/sh
### BEGIN INIT INFO
# Provides:       babeld
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:
# Default-Stop:   0 1 6
# Description:    Stops dnsmasq DHCP and DNS server (start, restart is done by vyatta cli)
### END INIT INFO

# Don't exit on error status
set +e

DAEMON=/usr/bin/babeld
NAME=babeld
DESC="Babeld routing service"

test -x $DAEMON || exit 0

# Provide skeleton LSB log functions for backports which don't have LSB functions.
if [ -f /lib/lsb/init-functions ]; then
         . /lib/lsb/init-functions
else
         log_warning_msg () {
            echo "${@}."
         }

         log_success_msg () {
            echo "${@}."
         }

         log_daemon_msg () {
            echo -n "${1}: $2"
         }

  log_end_msg () {
            if [ $1 -eq 0 ]; then
              echo "."
            elif [ $1 -eq 255 ]; then
              /bin/echo -e " (warning)."
            else
              /bin/echo -e " failed!"
            fi
         }
fi


start()
{
        # Return
 #   0 if daemon has been started
 #   1 if daemon was already running
 #   2 if daemon could not be started

        # /run may be volatile, so we need to ensure that
        # /run/dnsmasq exists here as well as in postinst

        if [ -f /var/run/babeld/babeld.pid ]; then
            kill "$(cat /var/run/babeld.pid)" 2>&1 > /dev/null
            rm -rf /var/run/babeld/babeld.pid > /dev/null
        fi

   $DAEMON -c /etc/babeld.conf -D -I /var/run/babeld.pid || return 2
}

stop()
{

 # Return
 #   0 if daemon has been stopped
 #   1 if daemon was already stopped
 #   2 if daemon could not be stopped
 #   other if a failure occurred
     if [ -f /var/run/babeld.pid ]; then
      kill "$(cat /var/run/babeld.pid)" 2>&1 > /dev/null
      rm -rf /var/run/babeld/babeld.pid > /dev/null
    fi
}

case "$1" in
  start)
    start
  ;;
  stop)
      stop
   ;;
  restart|force-reload)
      stop
      sleep 1
      start       
  ;;
   *)
       log_end_msg 1
       exit 1
       ;;
   esac
  
exit 0
